### ISSUE TITLE
how can I run this model on gpu 

### ISSUE THREAD

**Issue by traderpedroso** [stephenleo/heroku-apps#1]
I been trying to run the model over gpu on local from Mac from ubuntu and from Colab with different versions of Tensorflow and all give a error 

`WARNING:tensorflow:Layer lstm will not use cuDNN kernels since it doesn't meet the criteria. It will use a generic GPU kernel as fallback when running on GPU.`

**Comment by stephenleo** [comment]
Have you tried to pip install `tensorflow-gpu` instead of `tensorflow-cpu`?

**Comment by traderpedroso** [comment]
> Have you tried to pip install `tensorflow-gpu` instead of `tensorflow-cpu`?
yes I did and still
